CXX      = g++
CXXFLAGS = -std=c++0x -Ofast -funroll-loops -flto -fwhole-program -march=native -Wall -Weffc++
FILE     = main.cpp

all:
	$(CXX) $(CXXFLAGS) $(FILE) -o paraprog

clean:
	rm -fr paraprog
